name: sd-scripts (bmaltais)
run-name: sd-scripts (via ${{ github.event_name }})

on:
  # push:
  #   branches:
  #     - "main"
  #     - "kohya"
  #   paths:
  #     - "docker-bake.hcl"
  #     - "docker/Dockerfile.base"
  #     - "kohya/*"
  #     - ".github/workflows/build-push-kohya.yml"
  #     - "!**.md"

  workflow_dispatch:
    inputs:
      force-push:
        description: "push to GHCR"
        type: boolean
        required: true
        default: false

  # pull_request:
  #   paths:
  #     - "docker-bake.hcl"
  #     - "docker/Dockerfile.base"
  #     - "kohya/*"
  #     - ".github/workflows/build-push-kohya.yml"
  #     - "!**.md"

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

env:
  IMAGE_REGISTRY: ghcr.io
  IMAGE_NAME: neggles/kohya-ss-docker
  IMAGE_PLATFORMS: "linux/amd64"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        include:
          - name: "Latest"
            target: "kohya-latest"
            tags: |
              type=raw,value=latest,enable={{is_default_branch}}
              type=raw,value=latest-{{date 'YYYYMMDD'}},enable={{is_default_branch}}
              type=sha,prefix=latest-,format=short
              type=ref,event=branch,prefix=latest-
              type=ref,event=tag,prefix=latest-
              type=ref,event=pr,prefix=latest-

          - name: "Edge"
            target: "kohya-edge"
            tags: |
              type=raw,value=edge,enable={{is_default_branch}}
              type=raw,value=edge-{{date 'YYYYMMDD'}},enable={{is_default_branch}}
              type=sha,prefix=edge-,format=short
              type=ref,event=branch,prefix=edge-
              type=ref,event=tag,prefix=edge-
              type=ref,event=pr,prefix=edge-

    steps:
      - name: Free disk space
        id: free-disk-space
        run: |
          df -h .
          sudo find /usr/share/dotnet -delete
          sudo find /usr/local/lib/android -delete
          df -h .

      - name: Checkout
        id: checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: ${{ env.IMAGE_PLATFORMS }}

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: ${{ matrix.tags }}

      - name: Build and Push Versioned Tags
        id: build-push
        uses: docker/bake-action@v3
        with:
          targets: ${{ matrix.target }}
          files: |
            ./docker-bake.hcl
            ${{ steps.meta.outputs.bake-file }}
          push: ${{ (github.event_name == 'push' && github.ref == 'refs/heads/main') || inputs.force-push }}
          set: |
            *.cache-from=type=gha
